vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        product_images:
            uri_prefix: '%app.path.product_images%'
            upload_destination: images.storage  # '%kernel.project_dir%/public%app.path.product_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
