version: 2.1
workflows:
    build-dev:
        jobs:
            -   build:
                    context:
                        - stripe
jobs:
    build:
        machine:
            image: ubuntu-2004:202107-02
        environment:
            STRIPE_PUBLIC_KEY: $STRIPE_PUBLIC_KEY
            STRIPE_SECRET_KEY: $STRIPE_SECRET_KEY
        steps:
            - checkout
            -   run:
                    name: Run Docker
                    command: docker-compose up -d
            -   run:
                    name: Install PHP dependencies
                    command: docker-compose run composer sh -c "composer install && composer dump-autoload --optimize"
            -   run:
                    name: Install NodeJS dependencies
                    command: docker-compose run node sh -c "yarn install && yarn run build"
            -   run:
                    name: Prepare the database
                    command: |
                        docker-compose run php-fpm sh -c "wait-for-it.sh database:5432"
                        docker-compose run php-fpm sh -c "php bin/console doctrine:database:create --env=test"
                        docker-compose run php-fpm sh -c "php bin/console doctrine:schema:create --env=test"
                        docker-compose run php-fpm sh -c "php bin/console doctrine:fixtures:load --env=test --no-interaction"
            -   run:
                    name: Run tests
                    command: docker-compose run php-fpm bash -c "php ./bin/phpunit"
